# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "capistrano-eden"
  s.version = "0.0.1"
  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.date = "2012-07-20"
  s.description = "Defaults and recipes used in our deployments. Based on 'capistrano-helpers' gem."
  s.authors  = `git log --raw | grep Author: | awk -F ': | <|>' '{ print $2 }' | sort | uniq`.split("\n")
  s.email    = `git log --raw | grep Author: | awk -F ': | <|>' '{ print $3 }' | sort | uniq`.split("\n")
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "CHANGELOG.markdown",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "capistrano-eden.gemspec",
    "lib/capistrano-eden.rb",
    "lib/capistrano-eden/eden.rb",
    "lib/capistrano-eden/alx-structure.rb",
    "lib/capistrano-eden/b.rb",
    "lib/capistrano-eden/branch.rb",
    "lib/capistrano-eden/bundler.rb",
    "lib/capistrano-eden/check.rb",
    "lib/capistrano-eden/check_alx_site.rb",
    "lib/capistrano-eden/check_rails2.rb",
    "lib/capistrano-eden/check_rails3.rb",
    "lib/capistrano-eden/config_files.rb",
    "lib/capistrano-eden/gems.rb",
    "lib/capistrano-eden/git.rb",
    "lib/capistrano-eden/memcached.rb",
    "lib/capistrano-eden/multistage.rb",
    "lib/capistrano-eden/passenger.rb",
    "lib/capistrano-eden/php.rb",
    "lib/capistrano-eden/redis.rb",
    "lib/capistrano-eden/setup.rb",
    "lib/capistrano-eden/site-reference.rb",
    "lib/capistrano-eden/site-structure.rb",
    "lib/capistrano-eden/specs.rb",
    "lib/capistrano-eden/symlinks.rb",
    "lib/capistrano-eden/version.rb",
    "test/test_helper.rb"
  ]
  s.test_files = ["test/test_helper.rb"]
  s.homepage = "http://github.com/mv/capistrano-eden"
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.8.10}
  s.summary = %q{Defaults and recipes used in our deployments.}
  s.test_files = [
    "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<capistrano>, ["~> 2.12.0"])
    else
      s.add_dependency(%q<capistrano>, ["~> 2.12.0"])
    end
  else
    s.add_dependency(%q<capistrano>, ["~> 2.12.0"])
  end
end

